language: python
python:
  - 2.7
  - 3.5
  - 3.6
env:
  - NUMPY_VERSION=1.13

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.conda
    - $HOME/.cache/pyRSD

install:
    # Install and set up miniconda.
    - CONDA_INSTALL_LOCN="${HOME}/miniconda"
    - if [ $TRAVIS_OS_NAME == "linux" ]; then wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
    - if [ $TRAVIS_OS_NAME == "osx" ]; then wget http://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh; fi
    - bash miniconda.sh -b -p $CONDA_INSTALL_LOCN
    - export PATH=${CONDA_INSTALL_LOCN}/bin:$PATH
    - conda config --set always_yes true

    # pin conda verson to 4.3.22
  #  - conda config --set auto_update_conda False
#    - echo "conda ==4.3.22" >> ${CONDA_INSTALL_LOCN}/conda-meta/pinned

    - conda update --quiet conda

    # set the ordering of additional channels
    - conda config --prepend channels defaults
    - conda config --prepend channels nickhand
    - conda config --append channels bccp
    - conda config --append channels astropy
    - conda config --append channels conda-forge # for conda-build-all (will be moved to defaults soon)

    - conda install --yes swig gsl fftw gcc libgcc
    - conda install --yes numpy=$NUMPY_VERSION
    - echo "numpy $NUMPY_VERSION.*" >> ${CONDA_INSTALL_LOCN}/conda-meta/pinned
    - conda install --yes --file requirements.txt

    - export CC=gcc
    - export CXX=g++

    # install
    - pip install -r requirements-tests.txt
    - pip install .[tests]

    # To ease debugging, list installed packages
    - conda info -a

script:
    - python runtests.py --mpl

deploy:
  - provider: pypi
    distributions: sdist
    user: "nickhand"
    password:
      secure: "ZSH8om20Ucpk6HZNwiVA+LJdLheb0/NCdQgLFjnZGZCthl6XDYY/fVnchdpfMB1ucxmqcF83x2EdAqmak2kZlqSqQFUcSjl8YfG9UERSDpctzH0JtECq8/ejJibBdcgTJJRgDkjA7iItVce7SWrGK3ku1JpL3RHGSoIZL+cF74P7LXWp89vwz2A6vi/SSq9fYrG0pPi3jpP2GKsFZM/UDJCRaO6lXGEaZju5zGnmoj4IlgJ22YkDk1+9WH+GBR8/d5onFgBfFlqswMHPkmnCn5VzrMkqa1M1NtOYVSRFhqLy9PcV+5upG/KflYnOBcZYgYLz5tD1kly/maW5f3Vv3Z8aFnbARn9ckVin6rOodgug9bhlrDW+K0lwnoR3AF057wi1AzDCsiv9drSvFyAiJ5Zz6BeEqQvcjIhe4GEYUE9cvUDicgZO+Pf3tS3WNZM2s1EqeqVK86ZDLrF0Nwv+F5BpyCRWaWbiVU2h8Bc4WZV+2OghvpEWgaBu3d7zgfQX3a3U3DrAzCHOeHlfcD8pPw3L2LKwjGnmDZ/rCX+7FsMsaPv9rHnSUWRuTLh494rs6FAGEUuzvTK1PjIxvsvEUuVnx6NLvcJvDFM6pKX0wMUe7KZ00k9uRSdrUkcLOX7yNU/Aq1zYOfM1msS/Ags4hKRvzNbtPPFvnuKrF4d3JYg="
    on:
      tags   : true
      condition : ${TRAVIS_JOB_NUMBER##*.} == 1
