language: python
python:
- 2.7
- 3.5
env:
- NUMPY_VERSION=1.11
cache:
  directories:
  - $HOME/.cache/pip
  - $HOME/.conda
  - $HOME/.cache/pyRSD
before_install:
- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
- chmod +x miniconda.sh
- ./miniconda.sh -b -p $HOME/miniconda
- export PATH=$HOME/miniconda/bin:$PATH
- conda update --yes conda
install:
- conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
- source activate test
- conda config --add channels astropy
- conda config --add channels bccp
- conda config --prepend channels nickhand
- conda config --append channels conda-forge
- conda install --yes swig gcc gsl fftw libgcc
- conda install --yes numpy=$NUMPY_VERSION
- echo "numpy $NUMPY_VERSION.*" >> $CONDA_PREFIX/conda-meta/pinned
- conda install --yes --file requirements.txt
- pip install -r requirements-tests.txt
- pip install .[tests]
script:
- python runtests.py --mpl
deploy:
  provider: pypi
  skip_upload_docs: true
  user: nickhand
  password:
    secure: PAi3JFQW+XsQIou0PUh37kJqYwub35WU+JmJlKUZHSeRFurfYcJz7KfoMb1DJ3tEBrzk/yipFLO3PNE6YaCOjY6658Uwf2yNQns3tzKthSWLEXrFRIHb79c8pf4fv/+5xG0RN23OaFrZYNEddjbGbvoOjPUbJ2NxTdyR16PKWTK5yVn3JvHKoZJG23FXO+sHtZNtLEa1nr5CA7gAOsIb6Z4CHKJs2h4q1y3N+PvgnjC7aTPcl1LsayADAeLFqqA0wtk+uqt6Sj8zmYeP1JHaIN1mcTqbhz1WoVUN0M5AIg/xI/ofJiPNXEoBfzHpaygXZqGXHomH4LI+1WJMxz24Ess8rdIuWHC+vHTebzoAD9HHwrXTAUPDpX9SKCwBxDnJTmAUHuw6jN8uEZr0i34XPZrdc8v8PZgzifRKnoQBYlj/f5BJHO/PinT8b8HGL2+gvwqOJ8/+mQsR6WrDOqYu/EjzXzOc0GeePVHIEGdp0yhKdwQkoEu/ARZ25SQlmL0SvXDi8G/aESVsE8R0NEP58EyfONTT6vCVjwwjIgNKSVXxDUQbZO6lptdWBamZtKSBb+Zz294QVKLGT5H6EN61WW48TuVz7+0UWaMofM9DJ0M9YqfltnqgfmakLWms+Ie6cRSTyQxYwrXT9bzJMUq9GgR40QGW1Wle6K34PAUD5nI=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: nickhand/pyRSD
    condition : $TRAVIS_PYTHON_VERSION = "2.7"
