package:
  name: pyrsd
  version: {{version}}
source:
  git_url: https://github.com/nickhand/pyRSD.git
  git_tag: master

build:
  number: 0

requirements:
  build:
  - python
  - setuptools
  - gcc
  - gsl

  run:
  - python
  - numpy
  - pandas
  - scipy
  - george
  - scikit-learn >=0.17
  - emcee
  - mpi4py
  - libgcc
  - fftw

test:
  imports:
  - pyRSD
  - pyRSD.rsd

about:
  home: http://github.com/nickhand/pyRSD
  license: GPL3
  summary: Anisotropic RSD Fourier space modeling in python
  license_family: GPL3

extra:
  recipe-maintainers:
  - nickhand
