

package:
  name: george
  version: 0.2.1

source:
  fn: george-0.2.1.tar.gz
  url: https://pypi.io/packages/source/g/george/george-0.2.1.tar.gz
  md5: 4a050211e9f0dc3e042f46e7a3d245ba

build:
  number : 0

requirements:
  build:
    - python
    - setuptools
    - eigen3
    - numpy

  run:
    - python
    - setuptools
    - eigen3
    - numpy
    - scipy

test:
  requires:
    - nose
  imports:
    - george
    - george.testing
  commands:
    # I'm not sure why, but nosetests george.testing does not run any tests,
    # so I need to call out each module separately
    - nosetests george.testing.test_basic
    - nosetests george.testing.test_kernels
    - nosetests george.testing.test_tutorial

about:
  home: https://github.com/dfm/george
  license:  MIT License
  summary: 'Blazingly fast Gaussian Processes for regression.'
