# environment.yml
# Configuration file for creating a Conda Environment with dependencies needed for pyRSD.
# Create the environment by running the following command (after installing Miniconda):
#   $ conda env create --name pyrsd-docs-py27 -f environment.yml

name: pyrsd-docs-py27

channels:
- defaults
- nickhand
- astropy
- conda-forge

dependencies:
- python=2.7
- numpy
- pandas
- scipy
- george
- scikit-learn>=0.17
- emcee
- mpi4py
- six
- lmfit>=0.9
- autograd
- matplotlib
- seaborn
- corner
- pyrsd
- IPython
- sphinx_rtd_theme
- numpydoc
- sphinx
